version: '{branch}-{build}'

environment:
  matrix:
    - QTDIR: C:\Qt\5.13.0\mingw73_64
    - QTDIR: C:\Qt\5.13.0\mingw73_32
    - QTDIR: C:\Qt\5.13.0\msvc2015_64
    - QTDIR: C:\Qt\5.13.0\msvc2017
    - QTDIR: C:\Qt\5.13.0\msvc2017_64
    - QTDIR: C:\Qt\5.11.3\mingw53_32
    - QTDIR: C:\Qt\5.10.1\msvc2017_64
    - QTDIR: C:\Qt\5.10.1\winrt_armv7_msvc2017
    - QTDIR: C:\Qt\5.10.1\winrt_x86_msvc2017
    - QTDIR: C:\Qt\5.10.1\winrt_x64_msvc2017
    - QTDIR: C:\Qt\5.9.7\msvc2017_64
    - QTDIR: C:\Qt\5.9.7\winrt_armv7_msvc2017
    - QTDIR: C:\Qt\5.9.7\winrt_x86_msvc2017
    - QTDIR: C:\Qt\5.9.7\winrt_x64_msvc2017
    - QTDIR: C:\Qt\5.7.0\mingw53_32
    - QTDIR: C:\Qt\5.7.0\msvc2015

configuration:
  - debug
  - release

clone_script:
  - cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

install:
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if %QTDIR:msvc=%==%QTDIR% g++ --version
  - if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
  - if %QTDIR:msvc=%==%QTDIR% %make% --version
  - if not %QTDIR:msvc2013=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc2015=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe
  - if not %QTDIR:msvc=%==%QTDIR% %make% /? > nul

before_build:
  # Prepare the out-of-source build directory.
  - mkdir %APPVEYOR_BUILD_FOLDER%-build
  - qmake -o %APPVEYOR_BUILD_FOLDER%-build -r -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - echo 'QT -= gui' >> %APPVEYOR_BUILD_FOLDER%\ci-test-init.pri
  - '%make%'

test_script:
  # @todo output using Qt's -xunitxml option
  - if not %CONFIGURATION%==debug %make% check TESTARGS=-silent
